###############################################
### TMUX CONFIGURATION
###############################################

# Set default terminal to support true color
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Enable mouse support
set -g mouse on

# Use vi-style key bindings in copy mode
set-window-option -g mode-keys vi
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard

###############################################
### PREFIX AND KEY BINDINGS
###############################################

# Change default prefix key from Ctrl-b to Ctrl-s
unbind C-b
set -g prefix C-s

# Reload configuration
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded..."

# Pane navigation using Vim-style keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

###############################################
### STATUS BAR CONFIGURATION
###############################################

# Move status bar to the top
set-option -g status-position top

# Customize status bar style
set -g status-style bg=default
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

###############################################
### WINDOW CONFIGURATION 
###############################################


set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_number_position "right"


###############################################
### FZF CONFIGURATION
###############################################

TMUX_FZF_LAUNCH_KEY="C-f"


###############################################
### PLUGIN MANAGEMENT
###############################################

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
# set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'whame/tmux-modal'
set -g @plugin 'laktak/extrakto'
# set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-open'

# Initialize TMUX plugin manager (keep this at the bottom)
run '~/.tmux/plugins/tpm/tpm'
