[theme]
name = "catppuccin-mocha-mauve"

## enable or disable automatic update checks
update_check = true

## which search mode to use
## possible values: prefix, fulltext, fuzzy, skim
search_mode = "fuzzy"

## Which style to use. Possible values: auto, full and compact.
style = "auto"

## Invert the UI - put the search bar at the top.
invert = true

## Defaults to true. If enabled, upon hitting enter Atuin will immediately execute the command. Press tab to return to the shell and edit.
# This applies for new installs. Old installs will keep the old behaviour unless configured otherwise.
enter_accept = false

[stats]
# Set commands where we should consider the subcommand for statistics. Eg, kubectl get vs just kubectl
common_subcommands = [
  "apt",
  "cargo",
  "composer",
  "dnf",
  "docker",
  "git",
  "go",
  "ip",
  "kubectl",
  "nix",
  "nmcli",
  "npm",
  "pecl",
  "pnpm",
  "podman",
  "port",
  "systemctl",
  "tmux",
  "yarn",
]

# Set commands that should be totally stripped and ignored from stats
common_prefix = ["sudo"]

# Set commands that will be completely ignored from stats
ignored_commands = [
  "cd",
  "ls",
  "vi"
]

[sync]
# Enable sync v2 by default
# This ensures that sync v2 is enabled for new installs only
# In a later release it will become the default across the board
records = true

