# Eza aliases
alias la='eza -la'
alias ldot='eza -ld .*'
alias lD='eza -lD'
alias lDD='eza -laD'
alias ll='eza -l'
alias ls='eza'
alias lsd='eza -d'
alias lsdl='eza -dl'
alias lS='eza -l -ssize'
alias lT='eza -l -snewest'